# Generated by Django 5.1.4 on 2025-08-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapsecode101', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeworks_count', models.IntegerField(default=1)),
                ('lecture_count', models.IntegerField(default=1)),
                ('laboratory_count', models.IntegerField(default=0)),
                ('final_project_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('sources', models.TextField()),
                ('has_lab', models.BooleanField(default=False)),
                ('has_homework', models.BooleanField(default=True)),
                ('homework_description', models.TextField(default='')),
                ('lab_description', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='synapsecode101.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(max_length=100)),
                ('homework_uploaded', models.FileField(upload_to='homeworks/')),
                ('homework_rating', models.IntegerField()),
                ('homework_comment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='synapsecode101.courses')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='synapsecode101.lecture')),
            ],
        ),
    ]
